[katakana]
"あ" = "ア"
"い" = "イ"
"う" = "ウ"
"え" = "エ"
"お" = "オ"
"か" = "カ"
"き" = "キ"
"く" = "ク"
"け" = "ケ"
"こ" = "コ"
"さ" = "サ"
"し" = "シ"
"す" = "ス"
"せ" = "セ"
"そ" = "ソ"
"た" = "タ"
"ち" = "チ"
"つ" = "ツ"
"て" = "テ"
"と" = "ト"
"な" = "ナ"
"に" = "ニ"
"ぬ" = "ヌ"
"ね" = "ネ"
"の" = "ノ"
"は" = "ハ"
"ひ" = "ヒ"
"ふ" = "フ"
"へ" = "ヘ"
"ほ" = "ホ"
"ま" = "マ"
"み" = "ミ"
"む" = "ム"
"め" = "メ"
"も" = "モ"
"や" = "ヤ"
"ゆ" = "ユ"
"よ" = "ヨ"
"ら" = "ラ"
"り" = "リ"
"る" = "ル"
"れ" = "レ"
"ろ" = "ロ"
"わ" = "ワ"
"ゐ" = "ヰ"
"ゑ" = "ヱ"
"を" = "ヲ"
"ん" = "ン"
"ゔ" = "ヴ"
"が" = "ガ"
"ぎ" = "ギ"
"ぐ" = "グ"
"げ" = "ゲ"
"ご" = "ゴ"
"ざ" = "ザ"
"じ" = "ジ"
"ず" = "ズ"
"ぜ" = "ゼ"
"ぞ" = "ゾ"
"だ" = "ダ"
"ぢ" = "ヂ"
"づ" = "ヅ"
"で" = "デ"
"ど" = "ド"
"ば" = "バ"
"び" = "ビ"
"ぶ" = "ブ"
"べ" = "ベ"
"ぼ" = "ボ"
"ぱ" = "パ"
"ぴ" = "ピ"
"ぷ" = "プ"
"ぺ" = "ペ"
"ぽ" = "ポ"
"ぁ" = "ァ"
"ぃ" = "ィ"
"ぅ" = "ゥ"
"ぇ" = "ェ"
"ぉ" = "ォ"
"っ" = "ッ"
"ゃ" = "ャ"
"ゅ" = "ュ"
"ょ" = "ョ"
"ゎ" = "ヮ"
"ゕ" = "ヵ"
"ゖ" = "ヶ"
"・" = "・"
"ー" = "ー"
"゛" = "゛"
"゜" = "゜"
"、" = "、"
"う゛" = "ヴ"
"ゝ" = "ヽ"
"ゞ" = "ヾ"

[jisx0201]
"あ" = "ｱ"
"い" = "ｲ"
"う" = "ｳ"
"え" = "ｴ"
"お" = "ｵ"
"か" = "ｶ"
"き" = "ｷ"
"く" = "ｸ"
"け" = "ｹ"
"こ" = "ｺ"
"さ" = "ｻ"
"し" = "ｼ"
"す" = "ｽ"
"せ" = "ｾ"
"そ" = "ｿ"
"た" = "ﾀ"
"ち" = "ﾁ"
"つ" = "ﾂ"
"て" = "ﾃ"
"と" = "ﾄ"
"な" = "ﾅ"
"に" = "ﾆ"
"ぬ" = "ﾇ"
"ね" = "ﾈ"
"の" = "ﾉ"
"は" = "ﾊ"
"ひ" = "ﾋ"
"ふ" = "ﾌ"
"へ" = "ﾍ"
"ほ" = "ﾎ"
"ま" = "ﾏ"
"み" = "ﾐ"
"む" = "ﾑ"
"め" = "ﾒ"
"も" = "ﾓ"
"や" = "ﾔ"
"ゆ" = "ﾕ"
"よ" = "ﾖ"
"ら" = "ﾗ"
"り" = "ﾘ"
"る" = "ﾙ"
"れ" = "ﾚ"
"ろ" = "ﾛ"
"わ" = "ﾜ"
"ゐ" = "ｲ"
"ゑ" = "ｴ"
"を" = "ｦ"
"ん" = "ﾝ"
"ゔ" = "ｳﾞ"
"が" = "ｶﾞ"
"ぎ" = "ｷﾞ"
"ぐ" = "ｸﾞ"
"げ" = "ｹﾞ"
"ご" = "ｺﾞ"
"ざ" = "ｻﾞ"
"じ" = "ｼﾞ"
"ず" = "ｽﾞ"
"ぜ" = "ｾﾞ"
"ぞ" = "ｿﾞ"
"だ" = "ﾀﾞ"
"ぢ" = "ﾁﾞ"
"づ" = "ﾂﾞ"
"で" = "ﾃﾞ"
"ど" = "ﾄﾞ"
"ば" = "ﾊﾞ"
"び" = "ﾋﾞ"
"ぶ" = "ﾌﾞ"
"べ" = "ﾍﾞ"
"ぼ" = "ﾎﾞ"
"ぱ" = "ﾊﾟ"
"ぴ" = "ﾋﾟ"
"ぷ" = "ﾌﾟ"
"ぺ" = "ﾍﾟ"
"ぽ" = "ﾎﾟ"
"ぁ" = "ｧ"
"ぃ" = "ｨ"
"ぅ" = "ｩ"
"ぇ" = "ｪ"
"ぉ" = "ｫ"
"っ" = "ｯ"
"ゃ" = "ｬ"
"ゅ" = "ｭ"
"ょ" = "ｮ"
"ゎ" = "ﾜ"
"ゕ" = "ｶ"
"ゖ" = "ｹ"
"．" = "."
"，" = ","
"。" = "｡"
"・" = "･"
"ー" = "ｰ"
"゛" = "ﾞ"
"゜" = "ﾟ"
"、" = "､"
"「" = "｢"
"」" = "｣"
