# Migrating to github actions.
# I keep this least test setup as is, but won't add new things unless I cannot afford github actions bill.
language: rust
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
  - name: "Stable"
    rust: stable
    env: EXTRA_LINT_CHECK=1
  - name: "Beta"
    rust: beta
    env: EXTRA_LINT_CHECK=0
  - name: "Nightly"
    rust: nightly
    env: EXTRA_LINT_CHECK=0
cache:
  timeout: 300
  cargo: true
addons:
  apt:
    packages:
    - libxkbcommon-dev
before_script:
- rustup component add clippy
script:
- cargo build --verbose --all
- if [ $EXTRA_LINT_CHECK -gt 0 ]; 
  then cargo clippy -- -D warnings -A dead_code; 
  else cargo clippy;
  fi
- cargo test --verbose --all
