[package]
name = "cskk"
version = "0.0.1"
authors = ["Naoaki Iwakiri <naokiri@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
log = "0.4"
xkbcommon = "0.3"
bitflags = "1.0.4"
enum-display-derive = "0.1"
serde = "1.0.65"
serde_derive = "1.0.66"
serde_json = "1.0"
sequence_trie = {version = "0.3.6", features = ["serde"] }

[dev-dependencies]
env_logger = "*"


