[package]
name = "cskk"
version = "0.0.1"
authors = ["Naoaki Iwakiri <naokiri@gmail.com>"]


[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
log = "0.4"
xkbcommon = "0.3"
bitflags = "1.0.4"
toml = "0.4.6"
serde = "1.0.65"
serde_derive = "1.0.66"

[dev-dependencies]
env_logger = "0.5"


