# 全てのルールを列挙する。最初のものがデフォルトとして扱われる。
# UTF-8 only
# このrulesディレクトリごと $HOME/.local/share/libcskk/rules に移動してユーザー用にカスタマイズできる。
# entry: 規定の名前なので全てのエントリは[[entry]]で始まる。
[[entry]]
# name: Display name
name = "default"
# description: Display description for users
description = "default rule"
# path: directory path name to search rule.toml
path = "default"

#[[entry]]
#name = "UTF-8文字列"
#description = "UTF-8文字列"
#path = "UTF-8文字列だが、基本的にはascii文字のみ推奨"