name: Beta
# On every Sunday at 01:03
on:
  schedule:
    - cron: '3 1 * * 0'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  basic_check:
    uses: ./.github/workflows/basic_checks.yaml
    with:
      toolchain: "beta"
    secrets:
      gh_token: "${{ secrets.GITHUB_TOKEN }}"