name: Test
on: push

jobs:
  lint:
    name: lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true
      - name: Lint check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings -A dead_code
  build_and_test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        channel: [stable, nightly, beta]
        exclude:
          - os: macOS-latest
            channel: nightly
          - os: macOS-latest
            channel: beta
#          - os: windows-latest
#            channel: nightly
#          - os: windows-latest
#            channel: beta
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install required libs (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libxkbcommon-dev
      - name: Install required libs (MacOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew cask install xquartz
          brew install libxkbcommon
      - uses: actions/checkout@master
      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          profile: minimal
          override: true
      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
        
