name: Test
on: push

jobs:
  lint:
    name: lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true
      - name: Lint check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings -A dead_code -A improper_ctypes_definitions
  rust_test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: [stable, nightly, beta]
        exclude:
          - os: macOS-latest
            channel: nightly
          - os: macOS-latest
            channel: beta
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install required libs (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libxkbcommon-dev
      - name: Install required libs (MacOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew install --cask xquartz
          brew install libxkbcommon
      - uses: actions/checkout@master
      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          profile: minimal
          override: true
      - name: Run rust test
        uses: actions-rs/cargo@v1
        with:
          command: test
  library_test:
    name: library test
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cbindgen
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force cbindgen
      - name: Build library
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Generate c header
        run: cbindgen --config cbindgen.toml --crate cskk --output ./tests/libcskk.h
      - name: Build lib test
        run: gcc ./tests/basic.c -L ./target/debug/ -lcskk -o ./tests/lib_test
      - name: Run lib test
        run: LD_LIBRARY_PATH=./target/debug ./tests/lib_test
        
