name: Nightly
# On every Sunday at 03:03
on:
  schedule:
    - cron: '3 3 * * 0'
  workflow_dispatch:

jobs:
  basic_check:
    uses: ./.github/workflows/basic_checks.yaml
    with:
      toolchain: "nightly"
    secrets:
      gh_token: "${{ secrets.GITHUB_TOKEN }}"