name: Beta_Nightly
# On every Sunday at 01:03
on:
  schedule:
    - cron: '3 1 * * 0'
  workflow_dispatch:

jobs:
  lint:
    name: lint and format check
    strategy:
      matrix:
        channel: [ nightly, beta ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.channel }}
      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: Format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Lint check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings -A dead_code -A improper_ctypes_definitions
  rust_test:
    name: cargo test
    strategy:
      matrix:
        channel: [ nightly, beta ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.channel }}
      - name: Install required libs (Ubuntu)
        run: sudo apt-get install libxkbcommon-dev
      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          profile: minimal
          override: true
      - name: Run rust test
        uses: actions-rs/cargo@v1
        with:
          command: test