name: Stable Test
# On every Sunday at 02:03
on:
  schedule:
    - cron: '3 2 * * 0'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  basic_check:
    uses: ./.github/workflows/basic_checks.yaml
    with:
      toolchain: "stable"
    secrets:
      gh_token: "${{ secrets.GITHUB_TOKEN }}"